### ISSUE TITLE
 Running setup_vendor failed

### ISSUE THREAD

**Issue by jim-perkins** [CaseyBakey/chaosp#11]
and I stopped trying to run this script here.  I do appreciate all the work done though 

2020-12-10 19:24:17: Running setup_vendor
==================================
[-] Invalid '/home/jperkins/chaosp/chaosp/rattlesnake-os/vendor/android-prepare-vendor/crosshatch/sargo-qq3a.200805.001-factory-a1d05d06.zip' file

https://github.com/CaseyBakey/chaosp/blob/abf695ff0e87aa955a16873745638e4303d090c4/build.sh#L616

**Comment by CaseyBakey** [comment]
Sorry for the crappy code, it's obviously a forgotten hardcoded line here.

I did this to avoid downloading the OTA zip file again since android-prepare-vendor project doesn't check if the file is already downloaded/available...

I'm working on Android 11 right now and should push an update before the end of the month!

**Comment by CaseyBakey** [comment]
Closing it since it's fixed on branch 11.
