### ISSUE TITLE
Chrome build step fails due to git being unable to pull correct depot-tools branch

### ISSUE THREAD

**Issue by Bungeetaco** [CaseyBakey/chaosp#14]
Hi there!

First of all, thank you for creating this project & for maintaining it.

I have been attempting to create a build using CHAOSP for the past few days, but have been running into an issue at the time of building Chromium.

I had to edit `git pull origin master` to `git pull origin main` under the depot tools setup section, as this was failing the build and causing it to stop with the following error due to that branch apparently not existing or being recognized by git:

```==================================
2021-09-21 08:07:59: Running build_chromium
==================================
fatal: couldn't find remote ref master
```

The script might need to be edited to reflect this perhaps. Thought I'd create an issue to highlight this.

Thanks!

**Comment by CaseyBakey** [comment]
Fuuuuuuuuck it's because of all of this non-sense git rebranding of the master branch to main, to avoid hurting butt-hurted people -_-"

See there: https://github.com/github/renaming

I'll try to fix that this week-end!

edit: I just did try to issue "git pull origin master" and it's working. Maybe the chromium team recently renamed master to main, leading to your error, but realized they needed to add back master branch (pointing to main) to avoid errors everywhere :p

**Comment by CaseyBakey** [comment]
Should be fixed by [this](https://github.com/CaseyBakey/chaosp/commit/198df62835661ca1a130ffa85d2e98a58a6194d6) ;)
