### ISSUE TITLE
Make MicroG an option during the build.

### ISSUE THREAD

**Issue by AreYouLoco** [CaseyBakey/chaosp#15]
As stated in the title. Maybe you could add support for microg? Or point me how to integrate it in the build process. Thx for your work!

**Comment by CaseyBakey** [comment]
Hello there

microg was in fact included in the RattlesnakeOS custom config repo example (https://github.com/RattlesnakeOS/example-custom-config-repo) but I did get rid of it since I wasn't satisfied with it.

Take a look at [my fork](https://github.com/CaseyBakey/example-custom-config-repo/commits/chaosp_11) that is used when compiling CHAOSP, and particularly ([this commit](https://github.com/CaseyBakey/example-custom-config-repo/commit/6df170cc06b3eea7fdf224ff5dfc99ec2fa2d0d9) and [this commit](https://github.com/CaseyBakey/example-custom-config-repo/commit/2e7397563cee69fefa8debb315cf6a1bc4a81089))

You can fork your own version of this repo, reverting my commits about microg to try it out.

If you manage to make it working and make it conditional, I would accept your PR.

Regards ;)

**Comment by arolano** [comment]
FWIW there appears to be now several "flavors" of MicroG with varying restrictiveness (one by CalyxOS which seems to restrict it to Google Play's stuff by packagename, and one by nickrbogdanov which checks by fingerprint.

So maybe ideally someone could make it possible to choose the implementation 

https://github.com/RattlesnakeOS/microg/issues/4

**Comment by arolano** [comment]
Done a fork with MicroG re-enabled 

I changed the variable in build.sh to my forked example-custom-config-repo.git with those commits reverted.

Do I need to supply any option to make it build with MicroG or do I just need to "go and build" now ?

**Comment by CaseyBakey** [comment]
If you didn't create such option, I guess you don't have to call it
